### ISSUE TITLE
Thumbnails missing

### ISSUE THREAD

**Issue by jojoob** [Opencast-Moodle/moodle-repository_opencast#17]
When setting the channelid to 'engage-player' and select 'Embedd URL to player' videos are listed but without a thumbnail.
Hast the 'Preferred flavor to get thumbnail' setting something to do with this or is it a bug?

When setting 'channelid' to 'api' thumbnails are displayed.

These are my settings:

![repository_opencast settings](https://user-images.githubusercontent.com/4180675/133589541-722b2e29-efb6-4cec-9e42-e1f9408b1e48.png)

**Comment by jojoob** [comment]
Someone on the mailing list had the same (or similar?) problem a while ago: https://groups.google.com/a/opencast.org/g/moodle-opencast/c/AvjxCRA7-aM/m/j8WX8pfMBQAJ

**Comment by TamaraGunkel** [comment]
Hey,
I'm not sure if that's still relevant but it's not a bug. The plugin depends on the publications in the configured channel. The `engage-player` channel probably doesn't publish thumbnails which is why you don't see any. That's something you could configure in your Opencast workflow. The flavor setting is used for selecting the correct thumbnail image from the channel if there are multiple thumbnails.

**Comment by jojoob** [comment]
Thank you for the answer. Yes, this is still an issue.

So, when this is a configuration thing it should probably documented. Can you tell me how to configure this plugin and an Opencast workflow to get thumbnails displayed?

**Comment by jojoob** [comment]
This is not a problem anymore with Opencast 11 and latest plugin version. Just tested this again with a new test setup.

Back then I had this problem with Opencast 10.

**Comment by jojoob** [comment]
I downgraded to Opencast 11.2 because of an other issue. With this version the problem still exists. I still don't know how to configure the Opencast Workflows to fix this.
